# 旅行プランニング コマンド設定ファイル

# ステップ参照用の正式名称定義（表記揺れ防止）
step_references:
  phase1-step1: "旅行企画・候補絞込み"
  phase2-step1: "複数ケース具体調査"
  phase3-step1: "詳細準備工程"

# 共通要素定義
common:
  base_tools: ["Read", "Write", "Edit", "Bash", "WebSearch", "WebFetch"]
  output_path: "~/Documents/planning_docs/travel_planning/"
  commands_output_dir: "~/.claude/commands/travel_planning"
  
  # WebSearch/WebFetch使用ガイドライン
  web_research_guidelines: |
    **WebSearch/WebFetch使用原則**:
    - Phase2-step1: 予約可能性・価格・営業状況の調査で必須使用
    - Phase3-step1: 現地最新情報・天気・交通情報の調査で必須使用
    - 推論や一般知識ではなく、必ず実際のソースから情報収集
    - 複数のソース（公式サイト、予約サイト、観光協会等）からの情報照合
    
  # ドキュメント出力標準フォーマット
  document_output_standards: |
    **調査結果ドキュメント必須要件**:
    1. 調査実施日時の明記
    2. 情報源URL・サイト名の完全記載
    3. 価格・予約状況の確認タイムスタンプ
    4. 予約可能な直接リンクの提供
    5. 情報源の信頼性評価（公式・準公式・第三者）
    6. 情報の有効期限・更新頻度の明記

# 個別要素（step別に比較可能な構造）
individual_elements:
  description:
    phase1-step1: "旅行コンセプト策定と候補地・候補日時の範囲絞込み"
    phase2-step1: "各候補での予約可能性調査と最終決定・予約実行"
    phase3-step1: "予約確定後の詳細準備工程と実行準備"

  overview:
    phase1-step1: |
      この手順では、旅行の **なぜ行くのか** という動機と **どんな旅行にしたいか** というコンセプトを明確化し、
      **候補地（2-4箇所程度）** と **候補日時の範囲** を絞り込みます。
      最終決定はせず、次ステップで具体調査する対象の範囲を設定することが目的です。
    phase2-step1: |
      Phase1で絞り込んだ各候補地×候補日時の組み合わせで、**予約可能性と詳細条件を並行調査**します。
      現実的な制約（予約状況・価格・交通）を踏まえた比較検討を行い、**最終決定と予約実行**まで進めます。
    phase3-step1: |
      予約確定後の **詳細準備工程** を実施します。持ち物リストに加え、現地最新情報調査、
      手続き確認、緊急時対応計画、当日行動スケジュール詳細化など、実行成功のための最終準備を行います。

  dependencies_check:
    phase1-step1: []
    phase2-step1: ["phase1-step1"]
    phase3-step1: ["phase2-step1"]

  specific_questions:
    phase1-step1:
      - "今回の旅行の主な目的は何ですか？（リラックス、観光、体験、学習など）"
      - "どんな旅行スタイルを希望していますか？（のんびり、アクティブ、文化重視など）"
      - "旅行で最も重視したいことは何ですか？"
      - "避けたいこと、苦手なことはありますか？"
      - "一緒に行く人はいますか？その人の希望も考慮する必要がありますか？"
      - "希望する宿泊施設のタイプはありますか？（高級ホテル、ビジネスホテル、旅館、民宿、ゲストハウス、リゾートホテル、温泉宿など）"
      - "宿泊施設で重視したいポイントは何ですか？（立地・アクセス、価格、設備・アメニティ、サービス品質、雰囲気・コンセプト、食事内容など）"
      - "希望する移動手段はありますか？（飛行機、新幹線・特急、高速バス、自家用車・レンタカー、船・フェリー、現地交通手段など）"
      - "移動手段で重視したいポイントは何ですか？（価格・コスト、移動時間・速度、快適性、利便性・アクセス、景色・体験、環境負荷など）"
      - "候補となる地域や国はありますか？（2-4箇所程度に絞り込み）"
      - "候補となる時期・期間はいつ頃ですか？（範囲で指定）"
      - "予算の大まかな上限はどの程度ですか？"
    phase2-step1:
      - "Phase1で絞り込んだ各候補地について、どの点を最も重視して比較したいですか？"
      - "予約の取りやすさと理想的な条件、どちらを優先しますか？"
      - "代替案や妥協できる点はありますか？"
      - "予約開始時期や締切に制約はありますか？"
      - "キャンセルポリシーをどの程度重視しますか？"
    phase3-step1:
      - "現地の最新情報で特に確認したい項目はありますか？"
      - "持参したい特別なものや制限のあるものはありますか？"
      - "健康面・安全面で特に気をつけることはありますか？"
      - "緊急時の連絡体制や保険の準備状況はどうですか？"
      - "出発前に完了すべき手続きや準備はありますか？"

  dependencies_from_to:
    phase1-step1:
      from: "なし（旅行計画の起点）"
      to: ["phase2-step1"]
    phase2-step1:
      from: ["phase1-step1"]
      to: ["phase3-step1"]
    phase3-step1:
      from: ["phase2-step1"]
      to: ["旅行実行"]

  interaction_points:
    phase1-step1: |
      - **旅行の本質的な目的の抽出が最重要**: 「なんとなく行きたい」ではなく、具体的な動機や期待を明確化してください
      - **候補地は2-4箇所程度に絞込み**: 多すぎると次ステップでの調査が困難、少なすぎると選択肢が不足
      - **候補日時は範囲指定**: 「3月中旬〜4月上旬」「夏休み期間」など、柔軟性を保った設定
      - **最終決定はしない**: 次ステップでの具体調査に必要な範囲設定に留める
    phase2-step1: |
      - **WebSearch/WebFetch必須の調査プロセス**: 推論や一般的な知識ではなく、必ずWebSearch/WebFetchを使って最新の実際の情報を収集する
      - **ソース基づく調査の徹底**: 予約サイト、公式サイト、観光協会等の具体的なソースから情報を取得
      - **各候補の並行調査を重視**: 一つずつではなく、複数候補を同時に調査して比較
      - **予約可能性を最優先**: 理想的な計画より、実際に予約できる現実的な選択肢を重視
      - **代替案の準備**: 第一希望が取れない場合のバックアッププランも同時に検討
      - **最終決定と予約実行**: WebSearch/WebFetch調査結果を基に決定し、実際の予約まで進める
    phase3-step1: |
      - **予約確定が前提**: Phase2で予約が完了していることを確認してから進める
      - **現地最新情報の重視**: 天気予報、交通情報、営業状況など、直近の情報を収集
      - **包括的な準備**: 持ち物だけでなく、手続き・連絡先・緊急時対応まで含めた準備
      - **実行成功の視点**: 当日スムーズに進行できることを最優先とした準備

# 全体フェーズ構造定義
phase_structure:
  enable_overview: true
  show_on_steps: ["phase1-step1"]
  
  phases:
    phase1:
      title: "Phase 1: 旅行企画・候補絞込み"
      description: "旅行コンセプトを策定し、候補地・候補日時を範囲指定"
      steps:
        - id: "phase1-step1"
          filename: "phase1-step1.md"
          description: "旅行企画・候補絞込み"
    
    phase2:
      title: "Phase 2: 複数ケース具体調査"
      description: "各候補での予約可能性を調査し、最終決定・予約実行"
      steps:
        - id: "phase2-step1"
          filename: "phase2-step1.md"
          description: "複数ケース具体調査"
    
    phase3:
      title: "Phase 3: 詳細準備工程"
      description: "予約確定後の実行準備と最終チェック"
      steps:
        - id: "phase3-step1"
          filename: "phase3-step1.md"
          description: "詳細準備工程"

# 段階的質問処理原則
sequential_questioning:
  principle: |
    **複数の質問がある場合の処理原則**：
    複数の項目について確認が必要な場合は、必ず一つずつ順番に処理し、各質問の回答を確認してから次の質問に進む。一度に全ての質問を提示することは避け、段階的なアプローチを取る。
  
  template_format: |
    ```
    [{purpose}]のため、まず最初の項目について番号で選択してください：

    ## {item_title}
    以下から該当するものを選んでください（複数選択可）：
    1. {option1_description}
    2. {option2_description}
    3. {option3_description}
    4. その他（具体的に記入：_______）
    ---
    User: 回答例: 1, 3
    （{item_title}の回答を確認後、次の項目について質問）

    ---

    ## {next_item_title}
    以下から最も近いものを選んでください：
    1. {option1_description}
    2. {option2_description}
    3. {option3_description}
    4. その他（具体的に記入：_______）

    ---
    User: 回答例: 2
    ```

# 次ステップガイド設定
next_step_guidance:
  enable: true
  guidance_instruction: |
    ### 🚀 次のステップガイド
    
    このステップで収集・整理した情報を基に、次の候補ステップを提案してください：
    
    **ガイド原則**:
    - 今回の成果物の内容に基づいて適切な次ステップを提案
    - 不要と思われるステップには理由とともにスキップ提案
    - 各候補ステップで何をするかを簡潔に説明
    - 実行コマンドを明示
    - 最終的な選択はユーザーに委ねる
    
    **スキップ判断基準例**:
    - 短期間・単純な旅行 → phase3-step1（詳細準備工程）をスキップ
    - 慣れた目的地・国内旅行 → phase3-step1を簡略化
    - 海外・長期・特殊な旅行 → 全ステップ実行推奨

# 特別な処理要素
special_processes:
  phase1-step1:
    core_concept_extraction: |
      ### 3. 旅行コンセプトの抽出と確認
      収集した情報から、まず**この旅行の本質を一行で表現**してください：
      
      ```
      まず、この旅行の本質を一言で表すとどのようなものでしょうか？
      数フレーズ程度（最大でも140文字以内）で、「どんな旅行なのか」の核心部分を教えてください。
      ※具体的な場所や詳細はphase1-step2で扱うため、ここでは旅行の本質のみに集中してください。
      
      例：
      - 心身リフレッシュのための温泉旅行
      - 歴史と文化を学ぶ教育的な旅行
      - 家族との絆を深める記念旅行
      - 新しい体験を求める冒険旅行
      - グルメを楽しむ食べ歩き旅行
      ```
  
  phase2-step1:
    multiple_case_investigation: |
      ### 3. 複数候補の並行調査
      **Phase1で設定した候補範囲での具体調査:**
      ```
      各候補地×候補日時の組み合わせを並行調査します：
      
      ## 予約可能性調査（WebSearch/WebFetch必須）
      **CRITICAL**: 全ての調査で推論ではなくWebSearch/WebFetchを使用してソース基づく情報収集を実施してください
      
      ### 宿泊施設調査
      - WebSearchで各候補地の宿泊施設空室状況を検索
      - 予約サイト（楽天トラベル、じゃらん、Booking.com等）をWebFetchで確認
      - 価格帯とキャンセルポリシーを具体的に調査
      
      ### 交通手段調査  
      - WebSearchで交通手段の予約状況・価格を検索
      - 航空会社・JR・バス会社の公式サイトをWebFetchで確認
      - 割引・早期予約特典の有無を調査
      
      ### アクティビティ・観光地調査
      - WebSearchで各候補地の観光情報を検索
      - 現地観光協会・施設公式サイトをWebFetchで最新情報確認
      - 予約必要性・営業状況・料金を具体的に調査
      
      （各候補について同時に調査し、ソース基づく比較表を作成）
      
      ## 現実的制約の確認
      - 予算内での実現可能性（調査した実際の価格基準）
      - 希望条件との適合度（WebFetch結果との照合）
      - 代替案・妥協点の検討（複数ソースからの情報基準）
      
      ## 調査結果ドキュメント出力要件
      **CRITICAL**: 全ての調査結果は以下の形式で出力し、ユーザーが後から確認・検証できるようにする：
      
      ### 必須記載事項
      - **調査日時**: 情報取得日時を明記
      - **情報源URL**: WebSearch/WebFetchで取得した全URLを記載
      - **サイト名・運営者**: 情報源の信頼性判断用
      - **価格・空室情報の確認日**: 変動する情報の取得タイミング
      - **予約リンク**: 実際の予約可能なダイレクトリンク
      
      ### 出力フォーマット例
      ```
      ## [候補地名] 調査結果
      **調査実施**: 2024年XX月XX日 XX:XX
      
      ### 宿泊施設
      - [ホテル名](直接URL) - 価格: XX,XXX円/泊
        - 情報源: [楽天トラベル](具体的URL)
        - 確認日時: 2024年XX月XX日 XX:XX
      
      ### 交通手段  
      - [交通手段](予約URL) - 価格: XX,XXX円
        - 情報源: [JR東日本](具体的URL)
        - 確認日時: 2024年XX月XX日 XX:XX
      ```
      
      （WebSearch/WebFetch調査結果を基に最終決定と予約実行）
      ```